## Graded Assignment 3

Integrating Feast Feature Store into the IRIS Pipeline

In this assignment, we need to add a feature store layer to our IRIS pipeline so that training and inference share a single, consistent source of engineered features - eliminating a common source of training/serving skew.

In [1]:
# For removing Deprecation Warning related to pyparsing
!pip install --upgrade matplotlib pyparsing

Requirement already satisfied: matplotlib in /opt/conda/lib/python3.10/site-packages (3.10.8)
Requirement already satisfied: pyparsing in /opt/conda/lib/python3.10/site-packages (3.3.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (2.2.6)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: python-dateutil>=2.7 in /opt/conda/lib/python3.10/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [2]:
import warnings
warnings.filterwarnings("ignore")

## Step 1: Install feast, scikit-learn

Install feast, gcp dependencies and scikit-learn

In [3]:
!pip install feast scikit-learn feast[gcp]

Requirement already satisfied: feast in /opt/conda/lib/python3.10/site-packages (0.60.0)
Requirement already satisfied: scikit-learn in /opt/conda/lib/python3.10/site-packages (1.7.2)
Requirement already satisfied: click<9.0.0,>=7.0.0 in /opt/conda/lib/python3.10/site-packages (from feast) (8.3.1)
Requirement already satisfied: colorama<1,>=0.3.9 in /opt/conda/lib/python3.10/site-packages (from feast) (0.4.6)
Requirement already satisfied: dill~=0.3.0 in /opt/conda/lib/python3.10/site-packages (from feast) (0.3.9)
Requirement already satisfied: protobuf>=4.24.0 in /opt/conda/lib/python3.10/site-packages (from feast) (6.33.4)
Requirement already satisfied: Jinja2<4,>=2 in /opt/conda/lib/python3.10/site-packages (from feast) (3.1.6)
Requirement already satisfied: jsonschema in /opt/conda/lib/python3.10/site-packages (from feast) (4.26.0)
Requirement already satisfied: mmh3 in /opt/conda/lib/python3.10/site-packages (from feast) (5.2.0)
Requirement already satisfied: numpy<3,>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from feast) (2.2.6)
Requirement already satisfied: pandas<3,>=1.4.3 in /opt/conda/lib/python3.10/site-packages (from feast) (2.3.3)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/conda/lib/python3.10/site-packages (from feast) (23.0.0)
Requirement already satisfied: pydantic>=2.10.6 in /opt/conda/lib/python3.10/site-packages (from feast) (2.12.5)
Requirement already satisfied: pygments<3,>=2.12.0 in /opt/conda/lib/python3.10/site-packages (from feast) (2.19.2)
Requirement already satisfied: PyYAML<7,>=5.4.0 in /opt/conda/lib/python3.10/site-packages (from feast) (6.0.3)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from feast) (2.32.5)
Requirement already satisfied: SQLAlchemy>1 in /opt/conda/lib/python3.10/site-packages (from SQLAlchemy[mypy]>1->feast) (2.0.46)
Requirement already satisfied: tabulate<1,>=0.8.0 in /opt/conda/lib/python3.10/site-packages (from feast) (0.9.0)
Requirement already satisfied: tenacity<9,>=7 in /opt/conda/lib/python3.10/site-packages (from feast) (8.5.0)
Requirement already satisfied: toml<1,>=0.10.0 in /opt/conda/lib/python3.10/site-packages (from feast) (0.10.2)
Requirement already satisfied: tqdm<5,>=4 in /opt/conda/lib/python3.10/site-packages (from feast) (4.67.1)
Requirement already satisfied: typeguard>=4.0.0 in /opt/conda/lib/python3.10/site-packages (from feast) (4.4.4)
Requirement already satisfied: fastapi>=0.68.0 in /opt/conda/lib/python3.10/site-packages (from feast) (0.128.0)
Requirement already satisfied: uvicorn<=0.34.0,>=0.30.6 in /opt/conda/lib/python3.10/site-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.34.0)
Requirement already satisfied: uvicorn-worker in /opt/conda/lib/python3.10/site-packages (from feast) (0.3.0)
Requirement already satisfied: gunicorn in /opt/conda/lib/python3.10/site-packages (from feast) (25.1.0)
Requirement already satisfied: dask>=2024.2.1 in /opt/conda/lib/python3.10/site-packages (from dask[dataframe]>=2024.2.1->feast) (2026.1.2)
Requirement already satisfied: prometheus_client in /opt/conda/lib/python3.10/site-packages (from feast) (0.24.1)
Requirement already satisfied: psutil in /opt/conda/lib/python3.10/site-packages (from feast) (5.9.3)
Requirement already satisfied: bigtree>=0.19.2 in /opt/conda/lib/python3.10/site-packages (from feast) (1.3.1)
Requirement already satisfied: pyjwt in /opt/conda/lib/python3.10/site-packages (from feast) (2.11.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.10/site-packages (from Jinja2<4,>=2->feast) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.10/site-packages (from pandas<3,>=1.4.3->feast) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.10/site-packages (from pandas<3,>=1.4.3->feast) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.10/site-packages (from pandas<3,>=1.4.3->feast) (2025.3)
Requirement already satisfied: h11>=0.8 in /opt/conda/lib/python3.10/site-packages (from uvicorn<=0.34.0,>=0.30.6->uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.16.0)
Requirement already satisfied: typing-extensions>=4.0 in /opt/conda/lib/python3.10/site-packages (from uvicorn<=0.34.0,>=0.30.6->uvicorn[standard]<=0.34.0,>=0.30.6->feast) (4.15.0)
Requirement already satisfied: httptools>=0.6.3 in /opt/conda/lib/python3.10/site-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.7.1)
Requirement already satisfied: python-dotenv>=0.13 in /opt/conda/lib/python3.10/site-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (1.2.1)
Requirement already satisfied: uvloop!=0.15.0,!=0.15.1,>=0.14.0 in /opt/conda/lib/python3.10/site-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (0.22.1)
Requirement already satisfied: watchfiles>=0.13 in /opt/conda/lib/python3.10/site-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (1.1.1)
Requirement already satisfied: websockets>=10.4 in /opt/conda/lib/python3.10/site-packages (from uvicorn[standard]<=0.34.0,>=0.30.6->feast) (15.0.1)
Requirement already satisfied: scipy>=1.8.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.10/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: google-api-core<3,>=1.23.0 in /opt/conda/lib/python3.10/site-packages (from feast[gcp]) (2.29.0)
Requirement already satisfied: googleapis-common-protos<2,>=1.52.0 in /opt/conda/lib/python3.10/site-packages (from feast[gcp]) (1.72.0)
Requirement already satisfied: google-cloud-bigquery<4,>=2 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (3.40.0)
Requirement already satisfied: google-cloud-bigquery-storage<3,>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from feast[gcp]) (2.36.0)
Requirement already satisfied: google-cloud-datastore<3,>=2.16.0 in /opt/conda/lib/python3.10/site-packages (from feast[gcp]) (2.23.0)
Requirement already satisfied: google-cloud-storage<3,>=1.34.0 in /opt/conda/lib/python3.10/site-packages (from feast[gcp]) (2.19.0)
Requirement already satisfied: google-cloud-bigtable<3,>=2.11.0 in /opt/conda/lib/python3.10/site-packages (from feast[gcp]) (2.35.0)
Requirement already satisfied: fsspec<=2024.9.0 in /opt/conda/lib/python3.10/site-packages (from feast[gcp]) (2024.9.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /opt/conda/lib/python3.10/site-packages (from google-api-core<3,>=1.23.0->feast[gcp]) (1.27.0)
Requirement already satisfied: google-auth<3.0.0,>=2.14.1 in /opt/conda/lib/python3.10/site-packages (from google-api-core<3,>=1.23.0->feast[gcp]) (2.47.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.10/site-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3,>=1.23.0->feast[gcp]) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /opt/conda/lib/python3.10/site-packages (from google-auth<3.0.0,>=2.14.1->google-api-core<3,>=1.23.0->feast[gcp]) (4.9.1)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (2.5.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (2.8.0)
Requirement already satisfied: packaging>=24.2.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (25.0)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /opt/conda/lib/python3.10/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /opt/conda/lib/python3.10/site-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery<4,>=2->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (1.76.0)
Requirement already satisfied: pandas-gbq>=0.26.1 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (0.30.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.0.4 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (1.5.0)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.12.4 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigtable<3,>=2.11.0->feast[gcp]) (0.14.3)
Requirement already satisfied: google-crc32c<2.0.0dev,>=1.5.0 in /opt/conda/lib/python3.10/site-packages (from google-cloud-bigtable<3,>=2.11.0->feast[gcp]) (1.8.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.3->feast) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->feast) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->feast) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->feast) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->feast) (2026.1.4)
Requirement already satisfied: pyasn1>=0.1.3 in /opt/conda/lib/python3.10/site-packages (from rsa<5,>=3.1.4->google-auth<3.0.0,>=2.14.1->google-api-core<3,>=1.23.0->feast[gcp]) (0.6.2)
Requirement already satisfied: cloudpickle>=3.0.0 in /opt/conda/lib/python3.10/site-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (3.1.2)
Requirement already satisfied: partd>=1.4.0 in /opt/conda/lib/python3.10/site-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (1.4.2)
Requirement already satisfied: toolz>=0.12.0 in /opt/conda/lib/python3.10/site-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (1.1.0)
Requirement already satisfied: importlib_metadata>=4.13.0 in /opt/conda/lib/python3.10/site-packages (from dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (8.7.1)
Requirement already satisfied: starlette<0.51.0,>=0.40.0 in /opt/conda/lib/python3.10/site-packages (from fastapi>=0.68.0->feast) (0.50.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.10/site-packages (from fastapi>=0.68.0->feast) (0.0.4)
Requirement already satisfied: anyio<5,>=3.6.2 in /opt/conda/lib/python3.10/site-packages (from starlette<0.51.0,>=0.40.0->fastapi>=0.68.0->feast) (4.12.1)
Requirement already satisfied: exceptiongroup>=1.0.2 in /opt/conda/lib/python3.10/site-packages (from anyio<5,>=3.6.2->starlette<0.51.0,>=0.40.0->fastapi>=0.68.0->feast) (1.3.1)
Requirement already satisfied: zipp>=3.20 in /opt/conda/lib/python3.10/site-packages (from importlib_metadata>=4.13.0->dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (3.23.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.10/site-packages (from pandas-gbq>=0.26.1->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (80.9.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq>=0.26.1->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (1.9.1)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from pandas-gbq>=0.26.1->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (1.2.4)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /opt/conda/lib/python3.10/site-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq>=0.26.1->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (2.0.0)
Requirement already satisfied: locket in /opt/conda/lib/python3.10/site-packages (from partd>=1.4.0->dask>=2024.2.1->dask[dataframe]>=2024.2.1->feast) (1.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.10/site-packages (from pydantic>=2.10.6->feast) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/conda/lib/python3.10/site-packages (from pydantic>=2.10.6->feast) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.10/site-packages (from pydantic>=2.10.6->feast) (0.4.2)
Requirement already satisfied: oauthlib>=3.0.0 in /opt/conda/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq>=0.26.1->google-cloud-bigquery[pandas]<4,>=2; extra == "gcp"->feast[gcp]) (3.3.1)
Requirement already satisfied: greenlet>=1 in /opt/conda/lib/python3.10/site-packages (from SQLAlchemy>1->SQLAlchemy[mypy]>1->feast) (3.3.0)
Requirement already satisfied: mypy>=0.910 in /opt/conda/lib/python3.10/site-packages (from SQLAlchemy[mypy]>1->feast) (1.19.1)
Requirement already satisfied: mypy_extensions>=1.0.0 in /opt/conda/lib/python3.10/site-packages (from mypy>=0.910->SQLAlchemy[mypy]>1->feast) (1.1.0)
Requirement already satisfied: pathspec>=0.9.0 in /opt/conda/lib/python3.10/site-packages (from mypy>=0.910->SQLAlchemy[mypy]>1->feast) (1.0.4)
Requirement already satisfied: tomli>=1.1.0 in /opt/conda/lib/python3.10/site-packages (from mypy>=0.910->SQLAlchemy[mypy]>1->feast) (2.4.0)
Requirement already satisfied: librt>=0.6.2 in /opt/conda/lib/python3.10/site-packages (from mypy>=0.910->SQLAlchemy[mypy]>1->feast) (0.8.1)
Requirement already satisfied: attrs>=22.2.0 in /opt/conda/lib/python3.10/site-packages (from jsonschema->feast) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.10/site-packages (from jsonschema->feast) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.10/site-packages (from jsonschema->feast) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /opt/conda/lib/python3.10/site-packages (from jsonschema->feast) (0.30.0)

In [4]:
!feast version

Feast SDK Version: "0.60.0"

In [5]:
!git init

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
Initialized empty Git repository in /home/jupyter/main_run/.git/

In [6]:
%%writefile .gitignore

# Ignore Feast local database files
feast_iris/feature_repo/data/*.db

# Ignore Jupyter checkpoints
.ipynb_checkpoints/

# Ignore the parquet file
feast_iris/feature_repo/data/iris_dataset.parquet

Writing .gitignore

In [7]:
!feast init --minimal feast_iris

Creating a new Feast repository in /home/jupyter/main_run/feast_iris.

## Step 2: Prepare the iris data

In [8]:
!gsutil cp gs://mlops-assignment-mlops-iitmadras-mainrun/data/raw/iris.csv iris.csv

Copying gs://mlops-assignment-mlops-iitmadras-mainrun/data/raw/iris.csv...
/ [1 files][  3.8 KiB/  3.8 KiB]
Operation completed over 1 objects/3.8 KiB.

In [9]:
!mkdir feast_iris/feature_repo/data

In [11]:
import pandas as pd

df = pd.read_csv("iris.csv") 

# Create a unique Entity ID
df['sample_id'] = range(1, len(df) + 1)
df['sample_id'] = df['sample_id'].astype('int64')

# Create an Event Timestamp (since static sp using timestamp of 1 month prior)
timestamp = pd.Timestamp.now(tz='UTC') - pd.Timedelta(days=30)
df['event_timestamp'] = timestamp

print(df)

# Save as Parquet
df.to_parquet("feast_iris/feature_repo/data/iris_dataset.parquet", index=False)
print("Data prepared and saved to iris_dataset.parquet")

     sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

     sample_id                  event_timestamp
0            1 2026-01-30 10:07:17.245830+00:00
1            2 2026-01-30 10:07:17.245830+00:00
2            3 2026-01-30 10:07:17.245830+00:00
3            4 2026-01-30 10:07:17.245830+00:00
4            5 2026-01-30 10:07:17.245830+00:00
..         ...                              ...
145        146 2026-01-30 10:07:17.245830+00:00
146        147 2026-01-30 10:07:17.245830+00:00
147        148 2026-01-30 10:07:17.245830+00:00
148        149 2026-01-30 10:07:17.245830+00:00
149        150 2026-01-30 10:07:17.245830+00:00

[150 rows x 7 columns]
Data prepared and saved to iris_dataset.parquet

## Step 3: Configure Feature Store

In [12]:
%%writefile feast_iris/feature_repo/feature_store.yaml
project: feast_iris
registry: data/registry.db
provider: local
online_store:
    type: sqlite
    path: data/online_store.db
entity_key_serialization_version: 3

Overwriting feast_iris/feature_repo/feature_store.yaml

## Step 4: Define Entities, Data Sources & Feature Views

In [13]:
%%writefile feast_iris/feature_repo/iris_features.py
from datetime import timedelta
from feast import Entity, FeatureView, Field, FileSource, ValueType
from feast.types import Float32, String

# Define the Data Source
iris_source = FileSource(
    path="data/iris_dataset.parquet", 
    timestamp_field="event_timestamp"
)

# Define the Entity
iris_entity = Entity(
    name="sample_id", 
    value_type=ValueType.INT64, 
    description="Unique identifier for an Iris flower sample"
)

# Define the Feature View
iris_feature_view = FeatureView(
    name="iris_features",
    entities=[iris_entity],
    ttl=timedelta(weeks=52),
    schema=[
        Field(name="sepal_length", dtype=Float32),
        Field(name="sepal_width", dtype=Float32),
        Field(name="petal_length", dtype=Float32),
        Field(name="petal_width", dtype=Float32),
        Field(name="species", dtype=String), 
    ],
    online=True,
    source=iris_source,
)

Writing feast_iris/feature_repo/iris_features.py

## Step 5: Apply Definitions & Materialize Features

In [14]:
%cd feast_iris/feature_repo
!feast apply

/home/jupyter/main_run/feast_iris/feature_repo
No project found in the repository. Using project name feast_iris defined in feature_store.yaml
Applying changes for project feast_iris
Created project feast_iris
Created entity sample_id
Created feature view iris_features

WARNING:root:Cannot use sqlite_vec for vector search
Created sqlite table feast_iris_iris_features

In [15]:
!ls data -la

total 36
drwxr-xr-x 2 jupyter jupyter  4096 Mar  1 10:09 .
drwxr-xr-x 5 jupyter jupyter  4096 Mar  1 10:09 ..
-rw-r--r-- 1 jupyter jupyter  6649 Mar  1 10:07 iris_dataset.parquet
-rw-r--r-- 1 jupyter jupyter 16384 Mar  1 10:09 online_store.db
-rw-r--r-- 1 jupyter jupyter   951 Mar  1 10:09 registry.db

In [16]:
# Materialize features in the online store upto current time
!feast materialize-incremental $(date -u +"%Y-%m-%dT%H:%M:%S")

Materializing 1 feature views to 2026-03-01 10:10:42+00:00 into the sqlite online store.

iris_features from 2025-03-02 10:10:49+00:00 to 2026-03-01 10:10:42+00:00:

In [17]:
!ls data -la

total 168
drwxr-xr-x 2 jupyter jupyter   4096 Mar  1 10:10 .
drwxr-xr-x 5 jupyter jupyter   4096 Mar  1 10:09 ..
-rw-r--r-- 1 jupyter jupyter   6649 Mar  1 10:07 iris_dataset.parquet
-rw-r--r-- 1 jupyter jupyter 151552 Mar  1 10:10 online_store.db
-rw-r--r-- 1 jupyter jupyter    975 Mar  1 10:10 registry.db

## Step 6: Fetch Features for Offline Training

In [18]:
%cd ..

import pandas as pd
from feast import FeatureStore

store = FeatureStore(repo_path="feature_repo")

# Create the entity dataframe
entity_df = pd.read_parquet("feature_repo/data/iris_dataset.parquet")[['sample_id', 'event_timestamp']]

# Fetch historical features
training_data = store.get_historical_features(
    entity_df=entity_df,
    features=[
        "iris_features:sepal_length",
        "iris_features:sepal_width",
        "iris_features:petal_length",
        "iris_features:petal_width",
        "iris_features:species"
    ]
).to_df()

training_data.head()

/home/jupyter/main_run/feast_iris

,sample_id,event_timestamp,sepal_length,sepal_width,petal_length,petal_width,species
0,1,2026-01-30 10:07:17.245830+00:00,5.1,3.5,1.4,0.2,setosa
1,97,2026-01-30 10:07:17.245830+00:00,5.7,2.9,4.2,1.3,versicolor
2,98,2026-01-30 10:07:17.245830+00:00,6.2,2.9,4.3,1.3,versicolor
3,99,2026-01-30 10:07:17.245830+00:00,5.1,2.5,3.0,1.1,versicolor
4,100,2026-01-30 10:07:17.245830+00:00,5.7,2.8,4.1,1.3,versicolor

In [19]:
%cd ..

import joblib
from sklearn.tree import DecisionTreeClassifier

print("Training the model...")
X_train = training_data[['sepal_length','sepal_width','petal_length','petal_width']]
y_train = training_data.species
mod_dt = DecisionTreeClassifier(max_depth = 3, random_state = 1)
mod_dt.fit(X_train,y_train)
joblib.dump(mod_dt, "model.joblib")

/home/jupyter/main_run
Training the model...

['model.joblib']

## Step 7: Fetch Features for Inference

In [20]:
%cd feast_iris

inference_request = [{"sample_id": 5}]

# Fetch features from the online store
online_features = store.get_online_features(
    features=[
        "iris_features:sepal_length",
        "iris_features:sepal_width",
        "iris_features:petal_length",
        "iris_features:petal_width",
    ],
    entity_rows=inference_request
).to_dict()

inference_df = pd.DataFrame(online_features)

inference_df = inference_df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

inference_df

/home/jupyter/main_run/feast_iris

   sepal_length  sepal_width  petal_length  petal_width
0           5.0          3.6           1.4          0.2

## Step 8: Doing Inference

In [22]:
%cd ..
model = joblib.load("model.joblib")
prediction = model.predict(inference_df)
print(f"Predicted Species: {prediction}")

/home/jupyter/main_run
Predicted Species: ['setosa']

In [ ]:
!gsutil cp -r Feast_Assignment.ipynb gs://ga-3-assignment-file-final-mlops-iitmadras